Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace contact_list.Models
{
    public class ContactModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace contact_list.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContactoController.cs
using contact_list.Data;
using contact_list.Models;
using contact_list.Repos;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace contact_list.Controllers
{
    public class ContactoController : Controller
    {
        private readonly IContactRepository _contactRepository;
        public ContactoController(IContactRepository contactRepository)
        {
            _contactRepository = contactRepository;
        }
        public IActionResult Index()
        {
           List<ContactModel> Contacts = _contactRepository.FindAll();
            return View(Contacts);
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit(int id)
        {
            ContactModel contact = _contactRepository.ListById(id);
            return View(contact);
        }

        public IActionResult ConfirmDelete(int id)
        {
            ContactModel contact = _contactRepository.ListById(id);
            return View(contact);
        }

        public IActionResult Delete(int id)
        {
            _contactRepository.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Create(ContactModel contact)
        {
            _contactRepository.Add(contact);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Edit(ContactModel contact)
        {
            _contactRepository.Update(contact);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using contact_list.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace contact_list.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contacto/ConfirmDelete.cshtml
@model ContactModel
@{
    ViewData["Title"] = "Confirm contact delete";
}

<div class="text-center">
  
    <h3>Are you sure you want to delete (@Model.Name)?</h3>    
    <a class="btn btn-outline-primary" role="button" asp-controller="Contacto" asp-action="Index">Cancel Delete</a>
    <a class="btn btn-outline-danger" role="button" asp-route-id="@Model.Id" asp-controller="Contacto" asp-action="Delete">Confirm Delete</a>
</div>

Views/Contacto/Create.cshtml
@model ContactModel
@{
    ViewData["Title"] = "Create New Contact";
}

<div class="text-center">
    <h1 class="display-4">Create new contact</h1>
</div>

<form asp-controller="Contacto" asp-action="Create" method="post">
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Enter the contact's name">
    </div>
    <div class="form-group">
        <label for="mail">E-mail</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Enter contact's name">
    </div>
    <div class="form-group">
        <label for="phone">phone-number</label>
        <input type="text" asp-for="Phone" class="form-control" placeholder="Enter contact's phone contact">
    </div>
    <button type="submit" class="btn btn-primary">Submit new contact</button>
    <a class="btn btn-secondary" asp-controller="Contacto" asp-action="Index" role="button">Return</a>
</form>

Views/Contacto/Edit.cshtml
@model ContactModel
@{
    ViewData["Title"] = "edit Contact";
}

<div class="text-center">
    <h1 class="display-4">Create new contact</h1>
</div>

<form asp-controller="Contacto" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group" >
        <label for="name">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Enter the contact's name">
    </div>
    <div class="form-group">
        <label for="mail">E-mail</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Enter contact's name">
    </div>
    <div class="form-group">
        <label for="phone">phone-number</label>
        <input type="text" asp-for="Phone" class="form-control" placeholder="Enter contact's phone contact">
    </div>

    <button type="submit" class="btn btn-primary">Submit change to contact</button>
    <a class="btn btn-secondary" asp-controller="Contacto" asp-action="Index" role="button">Return</a>
</form>

Views/Contacto/Index.cshtml
@model List<ContactModel>
@{
    ViewData["Title"] = "Contact List";
}

<div class="text-center">
    <div class=" d-grip gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-outline-primary" asp-controller="Contacto" asp-action="Create"> Add a new contact</a> 
    </div>
    <h1 class="display-4">Contact List</h1>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">name</th>
                <th scope="col">e-mail</th>
                <th scope="col">Contact</th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>

            @{
                if (Model != null && Model.Any())
                {
                    foreach (ContactModel contact in Model)
                    {
                        <tr>
                            <th scope="row">1</th>
                            <td>@contact.Name</td>
                            <td>@contact.Email</td>
                            <td>@contact.Phone</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a role="button" class="btn btn-outline-success" asp-route-id="@contact.Id" asp-controller="Contacto" asp-action="Edit">Edit</a>
                                    <a role="button" class="btn btn-outline-danger" asp-route-id="@contact.Id" asp-controller="Contacto" asp-action="ConfirmDelete">Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                }
            }

        </tbody>
    </table>


</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Contacts manager</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contacts editor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contacts editor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - contacts editor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>